//This file is part of the e2e project.We are using this file to test the Sign Up page of the app.
//The file contains the locators for the Sign Up page.
output.SignUp = {
    firsTimeBtn: 'First time? Get started', 
    minCharacterText: "Minimum 4 characters",
    maxCharacterText: "Maximum 20 characters",
    onlyCharacterText: "Only alphanumeric characters",
    lowercaseLetterText: "One lowercase letter",
    uppercaseLetterText: "One uppercase letter",
    nameField: 'Your name',
    emailField: 'Email',
    passwordField: 'Password',
    maleOption: 'Male',
    continueBtn: 'Continue',
    signUpTitle: "Sign up",
    createAccountBtn: "Create account",
    verificationSentText: "Verification email sent",
    emailVerifiedBtn: "I have verified my email",
    chooseGoalText: "Choose your first personal goal.",
    gonnaDoItBtn: "I'm gonna do it!",
    creatingRoutineText: "You're creating your routine, Lucas Oliveira",
    dontMissAchievementText: "Don't miss any achievement!",
    activateBtn: "Activate",
    planText: "Plan",
    greetingText: "Hi, Lucas Oliveira!",
    trainerIntroText: "I'm João and I'll be your personal trainer.",
    emailAlreadyInUseText: "This email is already in use!",
    invalidEmailText: "Please enter a valid email address",
  };