name: Maestro E2E Tests (Android & iOS)

on:
  push:
    branches: [main]

jobs:
  ios-tests:
    name: iOS Maestro Tests
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '16'
      - name: Run iOS tests
        run: npm run test:e2e:ios
        
        # Install any dependencies
      - name: Install Dependencies
        run: swift package resolve
        
      # Run tests on iPhone 14 Simulator with iOS 16.0
      - name: Run Tests on iPhone 14 Simulator (iOS 16.0)
        run: |
          xcodebuild test \
            -scheme 'Requestify' \
            -destination 'platform=iOS Simulator,name=iPhone 14,OS=16.0'