name: Maestro E2E Tests (Android & iOS)

on:
  push:
    branches: [main]

jobs:
  ios-tests:
    name: iOS Maestro Tests
    runs-on: macos-latest
    steps:
      - name: Hello World
        run: echo "Hello, iOS World!"
   