name: Maestro E2E Tests (Android & iOS)

on:
  push:
    branches: [main]
  pull_request:

env:
  MAESTRO_FOLDER: e2e/
  API_TOKEN: ${{ secrets.API_TOKEN }}

jobs:
  android-tests:
    name: Android Maestro Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up OpenJDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Install Android SDK
        uses: android-actions/setup-android@v3

      - name: Install Maestro
        run: |
          curl -Ls "https://get.maestro.mobile.dev" | bash
          echo "$HOME/.maestro/bin" >> $GITHUB_PATH

      - name: Start Android Emulator
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 30
          target: google_apis
          arch: x86_64
          profile: pixel
          disable-animations: true
          script: echo "Android emulator started"

      - name: Run Maestro Android Tests
        run: |
          adb devices
          BACKEND_URL="$BACKEND_URL" API_TOKEN="$API_TOKEN" maestro test "$MAESTRO_FOLDER"

  ios-tests:
    name: iOS Maestro Tests
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up OpenJDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Install Maestro
        run: |
          curl -Ls "https://get.maestro.mobile.dev" | bash
          echo "$HOME/.maestro/bin" >> $GITHUB_PATH

      - name: Start iOS Simulator
        run: |
          xcrun simctl shutdown all || true
          xcrun simctl boot "iPhone 14 Pro"

      - name: Run Maestro iOS Tests
        run: |
          xcrun simctl install booted
          BACKEND_URL="$BACKEND_URL" API_TOKEN="$API_TOKEN" maestro test "$MAESTRO_FOLDER"
