name: Maestro E2E Tests (Android & iOS)

on:
  push:
    branches: [main]
  pull_request:

env:
  MAESTRO_FOLDER: e2e/

jobs:
  android-tests:
    name: Android Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        api-level: [21, 23, 29]
        target: [default, google_apis]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up OpenJDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Install Android SDK
        uses: android-actions/setup-android@v3

      - name: Install Maestro
        run: |
          curl -Ls "https://get.maestro.mobile.dev" | bash
          echo "$HOME/.maestro/bin" >> $GITHUB_PATH

      - name: run tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          target: ${{ matrix.target }}
          arch: x86_64
          profile: Nexus 6
          script: ./gradlew connectedCheck

  ios-tests:
    name: iOS Maestro Tests
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up OpenJDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Install Maestro
        run: |
          curl -Ls "https://get.maestro.mobile.dev" | bash
          echo "$HOME/.maestro/bin" >> $GITHUB_PATH

      - name: Boot iOS Simulator & Install App
        run: |
          xcrun simctl shutdown all || true
          xcrun simctl boot "iPhone 14 Pro"
          xcrun simctl install booted "$IPA_PATH"

      - name: Run Maestro Tests on iOS
        run: |
          maestro test "$MAESTRO_FOLDER"
