name: Maestro E2E Tests (Android & iOS)

on:
  push:
    branches: [main]

jobs:
  ios-tests:
    name: iOS Maestro Tests
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Run iOS tests
        run: npm run test:e2e:ios